### ISSUE TITLE
ultra slow processing time for big files)

### ISSUE THREAD

**Issue by milecombo** [meegpipe/meegpipe#20] opened 2015-01-06 09:32 UTC
Processing time seems to scale up with the size of the data, up to an unacceptable level (estimated in the order of months). In addition, such extremely long jobs are prone to being stopped/crash for reaching processing limits.
We need a strategy to optimize the job sumbissions with respect to the number of threads dedicated to it, so as to make the best of our computing resources.

During the course of the holidays we run ~128 jobs (VICI project files), with raw data sizes ranging from ~ 45 to 70 Gb in mff format. These jobs were run on all nodes of the grid; from day 2 up to day 8, all jobs stopped being updated at different times, and presumably crashed, without printing any additional txt output from the matlab display:
-44 files did not reach more than 1% resampling
-2 files reached the 30 min periodic generation, but  these were outliers for being <1 Gb
-all remaining files stopped at some importing stage

 the pipe consisted of:
> 1- import from mff to pset ;
> 2- downsample from 1000 to 250 Hz with antialiazing;
> 3- bandpass+notch filter combined in one single FIR, ba filter
> 4- periodic event generation with 1/30 bpm; 
then for each 30 min chunk : 
>> 5- a channel rejection node,
>>  6- a channel interpolation node,
>> 7- a bad epochs rejection pipe , itself made of 
>>> a) periodic generation of 2 sec events with 1 sec overlap 
>>> b) bad epoch rejection 

What can be done, in terms of job submission and server schedules, to speed up the procesing time?
Please help, or the sleep data will remain an unmoveable mountain!

The grid specifics are here below
![screen shot 2015-01-06 at 11 07 19 am](https://cloud.githubusercontent.com/assets/6671316/5627108/6bed328c-9594-11e4-8d7c-26a4d2c5c965.png)

**Comment by milecombo** [comment] 2015-01-06 10:28
Below a report of another job schedule, again with unacceptable processing times.
We suspected that the procedure used by the nodes of the server for read-and-write could be too slow, so we decided to try to use only 8 dedicated processors on somerenserver, where the data is stored. To avoid too many matlab being opened, we are now also limiting to 8 the max num of jobs that can run in parallel.
We submit 7 jobs, all with a size of ~ 50 Gb.
After more than 15 hours, jobs are at the stage of 2-3% resampling.
To get over the whole dataset, ~200 more jobs should then be processed serially in groups of 8.
The thread will be updated again , but at the current pace , also this schedules seems unacceptably slow.

**Comment by milecombo** [comment] 2015-01-06 16:32
Even without antialising, the downsample node seems to be ultra slow. running one file of ~40 GB on the somerenserver, it took 50 min to convert to pset, and as of 2 hours it is stuck at the same starting point of the resampling node, not even reaching the 0% progress report. Currently CPU usage is 38% and memory usage about 1/6th of tot space.
It seems then that the real bottleneck is how MEEGPIPE handles large files...

**Comment by germangh** [comment] 2015-01-06 19:34
Can you point me to one of the files you are trying to downsample? It would also help to have a code snippet that allows me to reproduce the core of the problem so that I can find a solution? Please don't send me your whole pipeline/analysis scripts, just a short "toy" script that I can use to reproduce the problem, e.g. the slowness of the downsampling. 

Definitely the downsampling node without antialiasing should not be that slow. So there is something wrong somewhere. To make sure that the problem is not specific to the grid/somerenserver you can try downsampling one of the files on a workstation and see if the processing is very slow there as well.

**Comment by simon-shlomo** [comment] 2015-01-06 21:33
Maybe consider this..
1. Do you store data with channels along rows (as in EEGLAB)? This is not efficient because Matlab stores a matrix in memory along the columns, and it's more efficient to call the memory serial.
2. Did you consider using the GPU..? just a wild idea that very likely will mean re-coding a lot. 
3. I am not sure exactly have the pset memory map works (and how high the disk I/O is), but maybe you want to store in on a tmpfs mount instead on disk?
4. Matlab is not exactly good at garbage collection, so consider running each session on only a few files, then re-start a session on a new set of files.

**Comment by milecombo** [comment] 2015-01-07 10:44
Hi, below a shorter code to simply import from mff, downsample, and then filtering
>
close all; clear all; clear classes; %clc;
%%
%%%%%%%%%%%%%%%%%%%%%%%
%%%   SET PATHs     %%%
%%%%%%%%%%%%%%%%%%%%%%%
restoredefaultpath;
datapath.top='/data2/projects/ssmd-michele/analysis/ssmd_sleep/VICI_sleep/';
datapath.meegpipe= '/usr/local/toolbox/meegpipe/';
datapath.eeglab ='/usr/local/toolbox/eeglab/';
datapath.myfun='/home/mcolombo/m1kCODE/myscripts_local/';
datapath.sensors=[datapath.myfun 'fun4plots/sensors_EGI257_phys7.mat'];
datapath.output=[datapath.top 'dummy_vici_dsmp_' datestr(now,'yymmdd-HHMMSS')];

addpath(genpath(datapath.meegpipe));
addpath(genpath(datapath.eeglab));
meegpipe.initialize;
cd(datapath.top)
%%%%%%%%%%%%%%%%%%%%%%%
%%% IMPORT PACKAGES %%%
%%%%%%%%%%%%%%%%%%%%%%%
import meegpipe.node.*;
import misc.get_hostname;
import misc.dir;
import mperl.file.spec.catfile;
import mperl.file.find.finddepth_regex_match;
import somsds.link2files;
import rank_epoch_from_movin_win2.*
import rank_chan_from_movin_win2.*
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%    LINKS FROM RAW MFF     %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
mypattern= 'vici_\d+05_eeg_sleep_night\d+' %'(13.*night2)'
files = somsds.link2rec('vici', 'modality', 'eeg',   ...
    'cond_regex', 'sleep', 'file_regex', [ mypattern '.mff$'], 'folder', datapath.output);
%%
%%%%%%%%%%%%%%%%%%%%%%%%%
%%%      IMPORT       %%%
%%%%%%%%%%%%%%%%%%%%%%%%%
nodeList = {};
tmp=load(datapath.sensors);
mySensors = tmp.mySensors;
myImporter = physioset.import.mff('Sensors', mySensors); %/ MFF
myNode = meegpipe.node.physioset_import.new('Importer', myImporter);
nodeList = [nodeList {myNode}];
%%%%%%%%%%%%%%%%%%%%%%%%%
%%%   DOWNSAMPLE 250  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%
myNode = meegpipe.node.resample.new('OutputRate', 250,'Antialiasing',true);
nodeList = [nodeList {myNode}];
%%
%%%%%%%%%%%%%%%%%%%%%
%%%   SELECTION   %%%
%%%%%%%%%%%%%%%%%%%%%
myDataClassSel= pset.selector.sensor_class('Class', 'EEG');
myDataChanSel = pset.selector.sensor_idx(1:257);
eegSel = pset.selector.cascade( myDataClassSel, myDataChanSel );
%%%%%%%%%%%%%%%%%%%%%
%%%     FILTER    %%%
%%%%%%%%%%%%%%%%%%%%%
fs=250;
% NOTCH
cutoffs=[47/fs*2  53/fs*2] ;
order = firfilt.firwsord('hamming', fs, 2);
mywin= firfilt.windows('hamming', order + 1);
bn = firfilt.firws(order, cutoffs, 'stop', mywin );
Hn=dfilt.df2t(bn,1);
% LOW PASS
fs=250;
cutoffs=[70/fs*2] ;
order = firfilt.firwsord('hamming', fs, 10);
mywin= firfilt.windows('hamming', order + 1);
bh = firfilt.firws(order, cutoffs, 'low', mywin );
Hh=dfilt.df2t(bh,1);
% HIGH PASS
cutoffs=[0.5/fs*2] ;
order = firfilt.firwsord('hamming', fs, 0.3);
mywin= firfilt.windows('hamming', order + 1);
bl = firfilt.firws(order, cutoffs, 'high', mywin );
Hl=dfilt.df2t(bl,1);
% freqz([Hn Hh Hl], 1024, fs); % view filts separately
% UNITE
hd= dfilt.cascade(Hh, Hl, Hn);
[b,a]=hd.tf;
freqz(b,a, 1024*20, fs)% view filts combined
myFilt= filter.ba(b,a); % ('B',b,'A',1);
myNode = meegpipe.node.filter.new( 'DataSelector',  eegSel, 'Filter', myFilt,  'ShowDiffReport',   true, 'EpochDurReport',30);
nodeList =[nodeList {myNode}];
%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  BUILD PIPELINE   %%%
%%%%%%%%%%%%%%%%%%%%%%%%%
myPipe = pipeline.new(...
    'NodeList',         nodeList, ...
    'GenerateReport',   true, ...
    'Save',             true, ...
    'Name',             'dummy_dsmp', ...
    'OGE',              true ,...
    'Queue',            'meegpipe.q' ) % this que was created by Diederick, it uses 8 processors of somerenserver
% 'TempDir',          @() tempdir);  %

% files = misc.dir(datapath.output, 'mff$', false, false, true); % Pick only the mff files
cd(datapath.output),
%%
run(myPipe, files{1});

**Comment by milecombo** [comment] 2015-01-07 10:49
Since also the filtering on the whole datset it's slow, you can add this node to the previous pipeline after downsamplig
>
%%
%%%%%%%%%%%%%%%%%%%%%
%%%   SELECTION   %%%
%%%%%%%%%%%%%%%%%%%%%
myDataClassSel= pset.selector.sensor_class('Class', 'EEG');
myDataChanSel = pset.selector.sensor_idx(1:257);
eegSel = pset.selector.cascade( myDataClassSel, myDataChanSel );
%%%%%%%%%%%%%%%%%%%%%
%%%     FILTER    %%%
%%%%%%%%%%%%%%%%%%%%%
fs=250;
% NOTCH
cutoffs=[47/fs*2  53/fs*2] ;
order = firfilt.firwsord('hamming', fs, 2);
mywin= firfilt.windows('hamming', order + 1);
bn = firfilt.firws(order, cutoffs, 'stop', mywin );
Hn=dfilt.df2t(bn,1);
% LOW PASS
fs=250;
cutoffs=[70/fs*2] ;
order = firfilt.firwsord('hamming', fs, 10);
mywin= firfilt.windows('hamming', order + 1);
bh = firfilt.firws(order, cutoffs, 'low', mywin );
Hh=dfilt.df2t(bh,1);
% HIGH PASS
cutoffs=[0.5/fs*2] ;
order = firfilt.firwsord('hamming', fs, 0.3);
mywin= firfilt.windows('hamming', order + 1);
bl = firfilt.firws(order, cutoffs, 'high', mywin );
Hl=dfilt.df2t(bl,1);
% freqz([Hn Hh Hl], 1024, fs); % view filts separately
% UNITE
hd= dfilt.cascade(Hh, Hl, Hn);
[b,a]=hd.tf;
freqz(b,a, 1024*20, fs)% view filts combined
myFilt= filter.ba(b,a); % ('B',b,'A',1);
myNode = meegpipe.node.filter.new( 'DataSelector',  eegSel, 'Filter', myFilt,  'ShowDiffReport',   true, 'EpochDurReport',30);
nodeList =[nodeList {myNode}];

**Comment by germangh** [comment] 2015-01-11 22:07
Thanks guys for reporting this and for the test code. The problem is the way the disk is being accessed/writen to within the `resample` node. The implementation of the `resample` node is very naive and that was enough for smaller files but indeed it is not acceptable for larger files. The good news is that I think I can rewrite the node to speed up the resampling several orders of magnitude. It is difficult to anticipate how fast it will end up being but I would expect it to be no more than 3  or 4 times slower than doing the resampling on Netstation. I will try to have this ready during the coming week (most likely by next Saturday).

**Comment by milecombo** [comment] 2015-01-26 13:37
Hola German,
any progress with editing a new downsampling node for big files?

**Comment by germangh** [comment] 2015-01-26 23:34
Hey Michele,

Not yet... will let you know as soon as I have that solved.

German

From:  milecombo <notifications@github.com>
Reply-To:  meegpipe/meegpipe
<reply+001f996c5f1ab0a527164364e2a8323f7e1c2ad3aece485292cf0000000110de05339
2a169ce03304b46@reply.github.com>
Date:  Monday, January 26, 2015 at 2:37 PM
To:  meegpipe/meegpipe <meegpipe@noreply.github.com>
Cc:  German Gomez Herrero <german.gomezherrero@gmail.com>
Subject:  Re: [meegpipe] ultra slow processing time for big files) (#20)

**Comment by germangh** [comment] 2015-02-01 23:59
There is a new `decimate` node that should be faster than the `resample` node for downsampling. But the pitfall is that the `decimate` node does not do any anti-aliasing pre-filtering which means that you need to take care of that before using the decimate node. The `filter` node is likely to be very slow also for very large data files so I still have to fix that. Also the `decimate` node does not offer a dramatic speedup with respect to the `resample` node. In my tests it was 3 to 4 times faster. So I am not closing this issue yet.

**Comment by germangh** [comment] 2015-02-07 23:36
Making a much faster implementation of the `filter` node is not that easy. The culprit of the problem is the way `physioset` objects are stored in disk, which makes them quite efficient when operating in temporal chunks, but also makes channel-by-channel access very slow. I have changed slightly the implementation of the `filter` node so that instead of filtering channel-by-channel it filters in chunks of channels (commit 8c912cc2d7384271ae0a85cc34cfe3eccceb1f48). The higher the number of channels in each chunk the faster the processing, but of course you need to have enough memory to have all those channels in MATLAB's workspace. 

The number of channels in each chunk is controlled by option `pset.largest_memory_chunk` in meegpipe's main configuration file: [+meegpipe/meegpipe.ini](https://github.com/meegpipe/meegpipe/blob/master/%2Bmeegpipe/meegpipe.ini). 

I have increased the value of `pset.largest_memory_chunk` to 4GBs. You can try to increase it further if you feel that you have enough memory on your system. 

So, summarizing, if you want to downsample a very large data file you should do it like this:

`````
% A sample physioset with a sampling rate of 10000 Hz
myData = import(physioset.import.matrix('SamplingRate', 10000), randn(10, 100000));
% Low pass filter to prevent aliasing
myFilter = filter.lpfilt('fc', 100/(myData.SamplingRate/2))
myNode = meegpipe.node.filter.new('Filter', myFilter);
run(myNode, myData);
myNode = meegpipe.node.decimate.new('DownsampleBy', 4);
run(myNode, myData);
````

I am going to close this issue for now. Please try this solution and let me know if you can now downsample those huge sleep files in a reasonable amount of time.

**Closed** 2015-02-07 23:36 UTC
